'use client'
import { Fragment, useState, type ReactNode } from 'react'
import type { Block, Edition, Evidence as EvidenceData } from '@/lib/learn/document'
const evidenceLabels = {paper_report:'论文作者报告',release_report:'官方发布说明',teaching_example:'个人教学示意',site_reproduction:'本站复现实测'}
function Declaration({value,e}:{value:EvidenceData;e:Edition}) {return <div className="mt-2 break-words text-xs leading-6 text-gray-600"><strong>{evidenceLabels[value.evidenceType]}</strong>{value.claimSourceRefs.map((r,i)=>{const s=e.sources.find(s=>s.id===r.sourceId);return s?<a className="ml-2 text-blue-700 underline" key={i} href={s.url} target="_blank" rel="noopener noreferrer">[{r.sourceId}] {r.evidenceLocation}</a>:null})}{value.reproduction&&<p>复现：<a href={value.reproduction.artifactUrl} target="_blank" rel="noopener noreferrer" className="underline">结果记录</a> · {value.reproduction.runAt} · {value.reproduction.protocol}</p>}</div>}
function Evidence({ids,e}:{ids:string[];e:Edition}) {return <span className="ml-2 inline-flex flex-wrap gap-1">{ids.map(id=>{const s=e.sources.find(x=>x.id===id);return s?<a key={id} href={s.url} target="_blank" rel="noopener noreferrer" className="text-xs font-semibold text-blue-600 hover:underline">[{id}]</a>:null})}</span>}
function Chart({b,e}:{b:Extract<Block,{type:'chart'}>;e:Edition}) {
 const v2=e.version===2&&'dataOrigin' in b?b:null,max=Math.max(1,...b.points.map(p=>p.value))
 return <figure className="my-8 rounded-xl border p-5"><h3 className="font-bold">{b.title}</h3><p className="text-xs text-amber-700">{!v2||v2.dataOrigin==='illustrative'?'教学示例数据，非论文实验结果':v2.dataOrigin==='paper'?'论文作者报告数据，本站未声称复现':'本站复现实测数据，条件与结果记录见下方'}</p>
 {v2&&<><Declaration value={v2} e={e}/><p className="mt-3 break-words text-xs leading-6">横轴：{v2.xAxis} · 纵轴：{v2.yAxis}（{b.unit}） · {v2.experiment.metricDirection==='higher'?'越高越好':'越低越好'}<br/>样本：{v2.experiment.sampleSize} · 基线：{v2.experiment.baseline}<br/>条件：{v2.experiment.conditions}<br/>随机种子：{v2.experiment.randomSeed??'未报告'}</p></>}
 <div className="mt-5 space-y-4">{b.points.map(p=><div key={p.label} className="grid min-w-0 grid-cols-[minmax(0,5rem)_minmax(0,1fr)_auto] items-center gap-2 text-sm sm:grid-cols-[6rem_minmax(0,1fr)_5rem] sm:gap-3"><span className="break-words">{p.label}</span><div className="h-4 rounded bg-gray-100"><div className="h-full rounded bg-blue-500" style={{width:100*p.value/max+'%'}}/></div><span>{p.value} {b.unit}</span></div>)}</div>
 <details className="mt-4 text-sm"><summary className="cursor-pointer">{v2&&v2.dataOrigin!=='illustrative'?'查看原始数据表与条件':'查看示例数据表'}</summary><div className="overflow-auto"><table className="mt-3 w-full"><thead><tr><th scope="col" className="p-2 text-left">配置</th><th scope="col" className="p-2 text-left">{v2?.yAxis??'数值'}（{b.unit}）</th>{v2&&<><th scope="col">置信区间</th><th scope="col">具体出处</th></>}</tr></thead><tbody>{b.points.map((p,i)=>{const vp=v2?.points[i];return <tr key={p.label}><th scope="row" className="border-b p-2 text-left font-normal">{p.label}</th><td className="border-b p-2">{p.value} {b.unit}</td>{vp&&<><td className="border-b p-2">{vp.confidenceInterval?`${vp.confidenceInterval.low}–${vp.confidenceInterval.high}`:'未报告'}</td><td className="border-b p-2">{vp.claimSourceRefs.map(r=>r.sourceId+': '+r.evidenceLocation).join('; ')}</td></>}</tr>})}</tbody></table></div></details>
 <figcaption className="mt-4 text-sm text-gray-500">{b.caption}<Evidence ids={b.sourceIds} e={e}/></figcaption></figure>
}
type QuizControl = { answer: number | null; onAnswer: (answer: number) => void }
function Quiz({b,progress}:{b:Extract<Block,{type:'quiz'}>;progress?:QuizControl}){const [local,setA]=useState<number|null>(null),a=progress?progress.answer:local;return <section className="my-6 rounded-xl border border-blue-200 p-5"><h3 className="font-bold">{b.question}</h3><div className="mt-3 grid gap-2">{b.options.map((o,i)=><button type="button" key={i} aria-pressed={a===i} onClick={()=>progress?progress.onAnswer(i):setA(i)} className={'rounded-lg border px-4 py-2 text-left '+(a===i?'border-blue-500 bg-blue-50':'hover:bg-gray-50')}>{String.fromCharCode(65+i)}. {o}</button>)}</div>{a!==null&&<p role="status" className="mt-3 text-sm leading-7"><strong>{a===b.answerIndex?'回答正确。':'回答不正确。'}</strong>{b.explanation}</p>}</section>}
function View({b,e,quiz}:{b:Block;e:Edition;quiz?:QuizControl}){
 switch(b.type){
 case 'heading':return b.level===2?<h2 className="mb-5 mt-12 text-2xl font-bold">{b.text}</h2>:<h3 className="mb-3 mt-8 text-xl font-bold">{b.text}</h3>
 case 'paragraph':return <p className="my-5 leading-9">{b.text}<Evidence ids={b.sourceIds} e={e}/></p>
 case 'callout':return <aside className={'my-6 rounded-xl border-l-4 p-5 '+(b.tone==='warning'?'border-amber-400 bg-amber-50':'border-blue-400 bg-blue-50')}><strong>{b.title}</strong><p className="mt-2 leading-8">{b.text}<Evidence ids={b.sourceIds} e={e}/></p></aside>
 case 'diagram':return <figure className="my-8 rounded-xl border p-5"><h3 className="font-bold">{b.title}</h3><ol className="mt-4 grid gap-3 sm:grid-cols-2">{b.steps.map((s,i)=><li key={i} className="rounded-lg bg-gray-50 p-4"><span className="block text-xs text-blue-600">步骤 {i+1}</span><strong>{s.title}</strong><p className="mt-2 text-sm leading-6">{s.description}</p></li>)}</ol><figcaption className="mt-4 text-sm text-gray-500">{b.caption}<Evidence ids={b.sourceIds} e={e}/></figcaption></figure>
 case 'chart':return <Chart b={b} e={e}/>
 case 'code':return <figure className="my-8 overflow-hidden rounded-xl border"><div className="bg-gray-100 px-4 py-2 text-xs">{b.language} · 示例代码（未执行）</div><pre className="overflow-auto bg-gray-950 p-5 text-sm leading-6 text-green-300"><code>{b.code}</code></pre><figcaption className="p-4 text-sm">{b.caption}</figcaption></figure>
 case 'quiz':return <Quiz b={b} progress={quiz}/>
 }}
export default function LearnInteractive({edition:e,quizProgress,practiceControls}:{edition:Edition;quizProgress?:{answers:Record<string,number>;onAnswer:(index:number,answer:number)=>void};practiceControls?:ReactNode}){return <div className="post-content learn-article text-gray-800"><p className="learn-article-lead my-6 rounded-xl bg-indigo-50 p-5 leading-8">{e.lead}</p>{e.version===2&&<Declaration value={e.evidence} e={e}/>}<p className="text-xs leading-6 text-gray-500">来源链接与结构校验不等于独立复现。教学示意、作者报告和本站实测分别标注。</p>{e.blocks.map((b,i)=><Fragment key={i}><View b={b} e={e} quiz={quizProgress?{answer:quizProgress.answers[i]??null,onAnswer:answer=>quizProgress.onAnswer(i,answer)}:undefined}/>{e.version===2&&b.type!=='heading'&&b.type!=='code'&&'evidenceType' in b&&b.type!=='chart'&&<Declaration value={b} e={e}/>}</Fragment>)}
 <section className="my-10 rounded-xl border p-6"><h2 className="text-xl font-bold">{e.practice.title} · {e.practice.minutes} 分钟</h2><ol className="mt-4 list-decimal space-y-2 pl-5">{e.practice.steps.map((s,i)=><li key={i}>{s}</li>)}</ol><p className="mt-4"><strong>验收：</strong>{e.practice.acceptance}</p>{practiceControls}</section>
 <h2 className="mt-10 text-xl font-bold">三个关键收获</h2><ul className="my-4 list-disc space-y-2 pl-5">{e.takeaways.map((t,i)=><li key={i}>{t}</li>)}</ul>
 <h2 className="mt-10 text-xl font-bold">职业方向</h2><p className="my-4 leading-8">{e.careerTip}</p>
 <h2 className="mt-10 text-xl font-bold">其他进展</h2>{e.otherUpdates.map(o=>{const s=e.sources.find(x=>x.id===o.sourceId);return s?<Fragment key={o.sourceId}><p className="my-4 leading-8"><a href={s.url} target="_blank" rel="noopener noreferrer" className="text-blue-700 underline">{s.title}</a>：{o.summary}</p>{e.version===2&&'evidenceType' in o&&<Declaration value={o} e={e}/>}</Fragment>:null})}
 <h2 className="mt-10 text-xl font-bold">原始出处</h2><ol className="mt-4 space-y-3">{e.sources.map(s=><li key={s.id} className="break-words text-sm"><a href={s.url} target="_blank" rel="noopener noreferrer" className="text-blue-700 underline">[{s.id}] {s.title}</a><span className="ml-2 text-gray-400">{s.publishedAt.slice(0,10)}</span>{e.version===2&&'verification' in s&&<div className="mt-2 leading-7"><p>{s.authors.join('、')} · {s.organization} · {s.version} · {s.verification==='verified'?'已人工核对':'待复核'} · 核对时间 {s.checkedAt}</p><p>问题：{s.researchQuestion}</p><p>方法：{s.method}</p><p>数据：{s.experimentalData}</p><p>局限：{s.limitations}</p></div>}</li>)}</ol>{e.version===2&&<section className="my-8 rounded-xl border p-5"><h2 className="text-lg font-bold">版本与更正说明</h2>{e.revisions.length?e.revisions.map(r=><p className="mt-3 break-words text-sm leading-7" key={r.number}>修订 {r.number} · {r.correctedAt} · {r.summary}<br/>上一版本指纹：{r.previousFingerprint}</p>):<p className="mt-3 text-sm">首次发布，暂无更正。</p>}</section>}</div>}
