'use client'
import { useState } from 'react'
import type { Block, Edition } from '@/lib/learn/document'
function Evidence({ids,e}:{ids:string[];e:Edition}) {return <span className="ml-2 inline-flex flex-wrap gap-1">{ids.map(id=>{const s=e.sources.find(x=>x.id===id);return s?<a key={id} href={s.url} target="_blank" rel="noopener noreferrer" className="text-xs font-semibold text-blue-600 hover:underline">[{id}]</a>:null})}</span>}
function Quiz({b}:{b:Extract<Block,{type:'quiz'}>}){const [a,setA]=useState<number|null>(null);return <section className="my-6 rounded-xl border border-blue-200 p-5"><h3 className="font-bold">{b.question}</h3><div className="mt-3 grid gap-2">{b.options.map((o,i)=><button type="button" key={i} aria-pressed={a===i} onClick={()=>setA(i)} className={'rounded-lg border px-4 py-2 text-left '+(a===i?'border-blue-500 bg-blue-50':'hover:bg-gray-50')}>{String.fromCharCode(65+i)}. {o}</button>)}</div>{a!==null&&<p role="status" className="mt-3 text-sm leading-7"><strong>{a===b.answerIndex?'回答正确。':'回答不正确。'}</strong>{b.explanation}</p>}</section>}
function View({b,e}:{b:Block;e:Edition}){
 switch(b.type){
 case 'heading':return b.level===2?<h2 className="mb-5 mt-12 text-2xl font-bold">{b.text}</h2>:<h3 className="mb-3 mt-8 text-xl font-bold">{b.text}</h3>
 case 'paragraph':return <p className="my-5 leading-9">{b.text}<Evidence ids={b.sourceIds} e={e}/></p>
 case 'callout':return <aside className={'my-6 rounded-xl border-l-4 p-5 '+(b.tone==='warning'?'border-amber-400 bg-amber-50':'border-blue-400 bg-blue-50')}><strong>{b.title}</strong><p className="mt-2 leading-8">{b.text}<Evidence ids={b.sourceIds} e={e}/></p></aside>
 case 'diagram':return <figure className="my-8 rounded-xl border p-5"><h3 className="font-bold">{b.title}</h3><ol className="mt-4 grid gap-3 sm:grid-cols-2">{b.steps.map((s,i)=><li key={i} className="rounded-lg bg-gray-50 p-4"><span className="block text-xs text-blue-600">步骤 {i+1}</span><strong>{s.title}</strong><p className="mt-2 text-sm leading-6">{s.description}</p></li>)}</ol><figcaption className="mt-4 text-sm text-gray-500">{b.caption}<Evidence ids={b.sourceIds} e={e}/></figcaption></figure>
 case 'chart':{const max=Math.max(1,...b.points.map(p=>p.value));return <figure className="my-8 rounded-xl border p-5"><h3 className="font-bold">{b.title}</h3><p className="text-xs text-amber-700">教学示例数据，非论文实验结果</p><div className="mt-5 space-y-4">{b.points.map(p=><div key={p.label} className="grid grid-cols-[6rem_1fr_5rem] items-center gap-3 text-sm"><span>{p.label}</span><div className="h-4 rounded bg-gray-100"><div className="h-full rounded bg-blue-500" style={{width:100*p.value/max+'%'}}/></div><span>{p.value} {b.unit}</span></div>)}</div><details className="mt-4 text-sm"><summary className="cursor-pointer">查看示例数据表</summary><table className="mt-3 w-full"><tbody>{b.points.map(p=><tr key={p.label}><td className="border-b p-2">{p.label}</td><td className="border-b p-2">{p.value} {b.unit}</td></tr>)}</tbody></table></details><figcaption className="mt-4 text-sm text-gray-500">{b.caption}<Evidence ids={b.sourceIds} e={e}/></figcaption></figure>}
 case 'code':return <figure className="my-8 overflow-hidden rounded-xl border"><div className="bg-gray-100 px-4 py-2 text-xs">{b.language} · 示例代码（未执行）</div><pre className="overflow-auto bg-gray-950 p-5 text-sm leading-6 text-green-300"><code>{b.code}</code></pre><figcaption className="p-4 text-sm">{b.caption}</figcaption></figure>
 case 'quiz':return <Quiz b={b}/>
 }}
export default function LearnInteractive({edition:e}:{edition:Edition}){return <div className="post-content text-gray-800"><p className="my-6 rounded-xl bg-indigo-50 p-5 leading-8">{e.lead}</p>{e.blocks.map((b,i)=><View b={b} e={e} key={i}/>)}
 <section className="my-10 rounded-xl border p-6"><h2 className="text-xl font-bold">{e.practice.title} · {e.practice.minutes} 分钟</h2><ol className="mt-4 list-decimal space-y-2 pl-5">{e.practice.steps.map((s,i)=><li key={i}>{s}</li>)}</ol><p className="mt-4"><strong>验收：</strong>{e.practice.acceptance}</p></section>
 <h2 className="mt-10 text-xl font-bold">三个关键收获</h2><ul className="my-4 list-disc space-y-2 pl-5">{e.takeaways.map((t,i)=><li key={i}>{t}</li>)}</ul>
 <h2 className="mt-10 text-xl font-bold">职业方向</h2><p className="my-4 leading-8">{e.careerTip}</p>
 <h2 className="mt-10 text-xl font-bold">其他进展</h2>{e.otherUpdates.map(o=>{const s=e.sources.find(x=>x.id===o.sourceId);return s?<p key={o.sourceId} className="my-4 leading-8"><a href={s.url} target="_blank" rel="noopener noreferrer" className="text-blue-700 underline">{s.title}</a>：{o.summary}</p>:null})}
 <h2 className="mt-10 text-xl font-bold">原始出处</h2><ol className="mt-4 space-y-3">{e.sources.map(s=><li key={s.id} className="break-words text-sm"><a href={s.url} target="_blank" rel="noopener noreferrer" className="text-blue-700 underline">[{s.id}] {s.title}</a><span className="ml-2 text-gray-400">{s.publishedAt.slice(0,10)}</span></li>)}</ol></div>}
