-- 在 Neon 控制台执行一次即可
-- 增强用户个人资料字段

ALTER TABLE users ADD COLUMN IF NOT EXISTS location    VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS website     TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS github_url  TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS twitter_url TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS motto       VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS tech_stack  TEXT[] NOT NULL DEFAULT '{}';
ALTER TABLE users ADD COLUMN IF NOT EXISTS title       VARCHAR(100);
