import { act, fireEvent, render, screen, within } from '@testing-library/react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import StudyArticle from '@/components/learn/StudyArticle'
import ReadingHistory, { getReadingHistory, hasRead } from '@/components/sections/ReadingHistory'
import LearnCatalog from '@/app/learn/LearnCatalog'
import { LEARN_PROGRESS_KEY, parseLearningProgress, serializeLearningProgress, type LearningProgress } from '@/lib/learn/progress'
import { makeEdition } from './fixtures/learn-edition'

const edition = makeEdition('2026-10-09'), slug = 'daily-learn-2026-10-09', fingerprint = 'a'.repeat(64)
const props = { edition, slug, fingerprint }
const record: LearningProgress = { slug, title: edition.title, fingerprint, state: 'in_progress', answers: {}, practiceDone: false, position: 600, section: '工程研究章节 1', updatedAt: 1000, completedAt: null }
const correct = Object.fromEntries(edition.blocks.flatMap((b, i) => b.type === 'quiz' ? [[String(i), b.answerIndex]] : []))
const answerAll = () => screen.getAllByRole('button', { name: 'A. 结合来源和边界判断' }).forEach(button => fireEvent.click(button))
const practice = () => screen.getByRole('checkbox', { name: /我已动手完成/ })
const complete = () => screen.getByRole('button', { name: '标记本期已完成' })
beforeEach(() => { localStorage.clear(); window.history.replaceState({}, '', '/'); vi.spyOn(window, 'scrollTo').mockImplementation(() => {}) })
afterEach(() => { vi.restoreAllMocks(); vi.useRealTimers() })

describe('local study interactions', () => {
  it('keeps a visit unstarted and requires answers, practice and explicit completion; cancellation preserves learning', () => {
    render(<StudyArticle {...props}/>)
    expect(screen.getByText('未开始学习')).toBeInTheDocument()
    expect(localStorage.getItem(LEARN_PROGRESS_KEY)).toBeNull()
    expect(complete()).toBeDisabled()
    answerAll()
    expect(screen.getByText('学习中')).toBeInTheDocument()
    expect(complete()).toBeDisabled()
    fireEvent.click(practice())
    expect(screen.getByText('已确认实践')).toBeInTheDocument()
    fireEvent.click(complete())
    expect(screen.getByText('已完成')).toBeInTheDocument()
    const completed = parseLearningProgress(localStorage.getItem(LEARN_PROGRESS_KEY))[slug]
    expect(completed.completedAt).not.toBeNull()
    fireEvent.click(screen.getByRole('button', { name: '取消完成' }))
    expect(screen.getByText('已确认实践')).toBeInTheDocument()
    expect(parseLearningProgress(localStorage.getItem(LEARN_PROGRESS_KEY))[slug].completedAt).toBeNull()
    expect(practice()).toBeChecked()
  })
  it('restores selected answers on reload and cancels completion when an answer or practice changes', () => {
    localStorage.setItem(LEARN_PROGRESS_KEY, serializeLearningProgress({ [slug]: { ...record, state: 'completed', answers: correct, practiceDone: true, completedAt: 1000 } }))
    render(<StudyArticle {...props}/>)
    expect(screen.getAllByRole('button', { name: 'A. 结合来源和边界判断' }).every(b => b.getAttribute('aria-pressed') === 'true')).toBe(true)
    fireEvent.click(screen.getAllByRole('button', { name: 'B. 忽略来源直接推广' })[0])
    expect(screen.queryByText('已完成')).not.toBeInTheDocument()
    expect(complete()).toBeDisabled()
    answerAll(); fireEvent.click(complete()); fireEvent.click(practice())
    expect(screen.getByText('学习中')).toBeInTheDocument()
    expect(complete()).toBeDisabled()
  })
  it('retains old-version data until an explicit action and requires current-version answers', () => {
    localStorage.setItem(LEARN_PROGRESS_KEY, serializeLearningProgress({ [slug]: { ...record, state: 'completed', answers: correct, practiceDone: true, completedAt: 1000 } }))
    render(<StudyArticle {...props} fingerprint={'b'.repeat(64)}/>)
    expect(screen.getByText(/文章内容已有更正/)).toBeInTheDocument()
    expect(screen.getByText('未开始学习')).toBeInTheDocument()
    expect(parseLearningProgress(localStorage.getItem(LEARN_PROGRESS_KEY))[slug].fingerprint).toBe(fingerprint)
    fireEvent.click(screen.getByRole('button', { name: '开始学习' }))
    const current = parseLearningProgress(localStorage.getItem(LEARN_PROGRESS_KEY))[slug]
    expect(current.fingerprint).toBe('b'.repeat(64))
    expect(current.answers).toEqual({})
    expect(current.completedAt).toBeNull()
  })
  it('accepts cross-tab updates and storage clear, without uploading learning behavior', () => {
    const fetch = vi.spyOn(globalThis, 'fetch')
    render(<StudyArticle {...props}/>)
    localStorage.setItem(LEARN_PROGRESS_KEY, serializeLearningProgress({ [slug]: { ...record, answers: correct } }))
    fireEvent(window, new StorageEvent('storage', { key: LEARN_PROGRESS_KEY }))
    expect(screen.getByText('学习中')).toBeInTheDocument()
    expect(screen.getAllByRole('button', { name: 'A. 结合来源和边界判断' })[0]).toHaveAttribute('aria-pressed', 'true')
    localStorage.clear(); fireEvent(window, new StorageEvent('storage', { key: null }))
    expect(screen.getByText('未开始学习')).toBeInTheDocument()
    expect(fetch).not.toHaveBeenCalled()
  })
  it('keeps all answers in memory when reads work but every storage write fails', () => {
    vi.spyOn(Storage.prototype, 'setItem').mockImplementation(() => { throw new DOMException('Quota', 'QuotaExceededError') })
    render(<><ReadingHistory slug={slug} title={edition.title}/><StudyArticle {...props}/></>)
    fireEvent.click(screen.getByRole('button', { name: '开始学习' })); answerAll(); fireEvent.click(practice()); fireEvent.click(complete())
    expect(screen.getByText('已完成')).toBeInTheDocument()
    expect(screen.getByText(/本页仍可学习/)).toBeInTheDocument()
    expect(localStorage.getItem(LEARN_PROGRESS_KEY)).toBeNull()
  })
  it('survives blocked reads and malformed legacy history without changing its key', () => {
    localStorage.setItem('arc_reading_history', 'null')
    expect(hasRead(slug)).toBe(false)
    expect(getReadingHistory()).toEqual([])
    vi.spyOn(Storage.prototype, 'getItem').mockImplementation(() => { throw new DOMException('Denied', 'SecurityError') })
    render(<><ReadingHistory slug={slug} title={edition.title}/><StudyArticle {...props}/></>)
    expect(screen.getByText(/本页仍可学习/)).toBeInTheDocument()
    answerAll(); fireEvent.click(practice()); fireEvent.click(complete())
    expect(screen.getByText('已完成')).toBeInTheDocument()
  })
  it('saves article-relative position and section, and only resumes on an explicit command', async () => {
    vi.useFakeTimers()
    const view = render(<StudyArticle {...props}/>)
    const article = view.container.querySelector('.learn-article')!
    vi.spyOn(article, 'getBoundingClientRect').mockReturnValue(new DOMRect(0, -650, 1000, 5000))
    fireEvent.scroll(window)
    await act(async () => { await vi.advanceTimersByTimeAsync(1001) })
    expect(localStorage.getItem(LEARN_PROGRESS_KEY)).toBeNull()
    fireEvent.click(screen.getByRole('button', { name: '开始学习' })); fireEvent.scroll(window)
    await act(async () => { await vi.advanceTimersByTimeAsync(1001) })
    expect(parseLearningProgress(localStorage.getItem(LEARN_PROGRESS_KEY))[slug].position).toBe(650)
    expect(screen.getByRole('button', { name: /继续上次位置/ })).toBeInTheDocument()
    expect(window.scrollTo).not.toHaveBeenCalled()
    vi.spyOn(article, 'getBoundingClientRect').mockReturnValue(new DOMRect(0, 350, 1000, 5000))
    fireEvent.click(screen.getByRole('button', { name: /继续上次位置/ }))
    expect(window.scrollTo).toHaveBeenCalledWith({ top: 1000, behavior: 'instant' })
    view.unmount(); window.history.replaceState({}, '', '/?resume=1'); render(<StudyArticle {...props}/>)
    expect(window.scrollTo).toHaveBeenLastCalledWith({ top: 650, behavior: 'instant' })
  })
  it('resets only the selected edition while preserving old reading history', () => {
    localStorage.setItem('arc_reading_history', JSON.stringify([{ slug, title: edition.title, readAt: new Date().toISOString() }]))
    localStorage.setItem(LEARN_PROGRESS_KEY, serializeLearningProgress({ [slug]: record, other: { ...record, slug: 'daily-learn-2026-10-08' } }))
    vi.spyOn(window, 'confirm').mockReturnValueOnce(false).mockReturnValueOnce(true)
    render(<StudyArticle {...props}/>)
    fireEvent.click(screen.getByRole('button', { name: '重置本期学习' }))
    expect(screen.getByText('学习中')).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: '重置本期学习' }))
    expect(screen.getByText('未开始学习')).toBeInTheDocument()
    expect(Object.keys(parseLearningProgress(localStorage.getItem(LEARN_PROGRESS_KEY)))).toEqual(['daily-learn-2026-10-08'])
    expect(hasRead(slug)).toBe(true)
  })
  it('shows completed records separately from visits and filters only the current public page', () => {
    const second = { ...record, slug: 'daily-learn-2026-10-08', title: '第二期', updatedAt: 2000 }
    localStorage.setItem(LEARN_PROGRESS_KEY, serializeLearningProgress({ [slug]: { ...record, state: 'completed', practiceDone: true, completedAt: 1000 }, [second.slug]: second }))
    render(<LearnCatalog articles={[{ slug, title: edition.title, excerpt: edition.excerpt, topic: 'agent', date: edition.date }, { slug: second.slug, title: second.title, excerpt: '另一期', topic: 'agent', date: '2026-10-08' }]} topic={null} topicCounts={{ agent: 2 }} total={2} page={1} pageSize={24}/>)
    expect(within(screen.getByRole('region', { name: '本机学习记录' })).getByText('1')).toBeInTheDocument()
    expect(screen.getByRole('link', { name: /继续学习.*第二期/ })).toHaveAttribute('href', '/blog/'+second.slug+'?resume=1')
    fireEvent.change(screen.getByRole('combobox', { name: '当前页学习状态' }), { target: { value: 'completed' } })
    expect(screen.getByRole('region', { name: '历史精读' })).toHaveTextContent(edition.title)
    expect(screen.getByRole('region', { name: '历史精读' })).not.toHaveTextContent(second.title)
    fireEvent.change(screen.getByRole('combobox', { name: '当前页学习状态' }), { target: { value: 'practice' } })
    expect(screen.getByRole('region', { name: '历史精读' })).toHaveTextContent(second.title)
    expect(screen.getByRole('region', { name: '历史精读' })).not.toHaveTextContent(edition.title)
  })
})
